One-Hundred-Trials/Good-Harvest-Market

src/components/Button/Button.jsx

- Button 적용 시 스타일 지정을 위해 variant와 size를 작성해주어야하며 피그마의 에셋 이름과 동일하게 작업했습니다. 
사이즈 : lg, m, ms, s
스타일 : abled, disabled, active
ex) 큰 사이즈(lg)의 비활성화(disabled)된 버튼 : `<Button variant="disabled" size="lg">비활성화</Button>`
- 추후 상태관리를 위해 context.API를 활용하여 리팩토링을 시도해보려 합니다.
- 없음
- 작업 내역 : Button.jsx
- 원하는 스타일에 맞게 버튼을 불러와 사용할 수 있습니다.
close : #1

Style : Button 컴포넌트 UI 제작

---

src/components/Product/Product.jsx

- API로 데이터를 받아 올 수 있는 UI 틀만 제작을 진행했습니다.
- 이미지를 불러오는 과정에서 오류가 생겨 이미지가 누락되거나 로딩시간이 길어져도 전체 컨텐츠의 크기를 유지하기 위해 이미지를 감싸는 `div`를 사용했고 고정 높이 값을 지정해주었습니다.
- 사용자가 세로 비율이 짧은 이미지를 업로드했을 때 가운데 정렬이 될 수 있도록  `position`을 활용했습니다.
- 없음
- 작업 내역 : Product.jsx
- 추후 API로 가져올 사용자의 Product 데이터를 지정한 형태의 UI로 제공합니다.
close : #2

Style : Product 컴포넌트 UI 제작

---

src/components/Follow/Follow.jsx
src/components/Follow/FollowStyle.jsx
src/components/FollowersCount/FollowersCount.jsx
src/components/FollowersCount/FollowersCountStyle.jsx
src/components/FollowingsCount/FollowingsCount.jsx
src/components/FollowingsCount/FollowingsCountStyle.jsx
src/components/Profile/Profile.jsx
src/components/Profile/ProfileStyle.jsx
src/components/ProfileAccount/ProfileAccount.jsx
src/components/ProfileAccount/ProfileAccountStyle.jsx
src/components/ProfileImg/ProfileImg.jsx
src/components/ProfileImg/ProfileImgStyle.jsx
src/pages/Main/Home/Home.jsx
src/pages/Main/Profile/MyProfile/MyProfile.jsx

- Profile_component UI 제작했습니다.
- 이유 : 없음
- 작업 내역 : Profile.jsx
close : #3

Style: Profile_component UI 제작

---

src/components/Header/Header.jsx
src/components/Modal/Modal.jsx
src/components/Modal/ModalAlert/ModalAlert.jsx

- 모달 알림창을 사용할 수 있습니다
- 이유 : 없음
- 작업 내역 : src/components/Modal/ModalAlert/ModalAlert.jsx
- 모달 알림창을 사용할 수 있습니다
close : #7

Style : modal alert 컴포넌트 UI

---

src/components/Comment/CommentInput/CommentInput.jsx
src/components/Comment/CommentInput/CommentInputStyle.jsx

- 스타일 컴포넌트 파일을 분리했습니다.
- 컴포넌트명을 새 컨벤션에 맞게 수정했습니다.
- 이유 : 코드 가독성을 높이기 위해 수정했습니다.
- 작업 내역 : 
CommentInput.jsx 
CommentInputStyle.jsx
close : #6

Modify : Comment Input 스타일 컴포넌트 파일 분리

---

src/components/Button/Button.jsx
src/pages/Login/LoginEmail/LoginEmail.jsx
src/pages/Login/LoginEmail/LoginEmailStyle.jsx

- 밸리데이션 검증은 추후 기능 구현 시 넣을 예정입니다.
- Button 컴포넌트에서 정의된 스타일(BtnStyle)을 확장하고 싶어 아래와 같이 작성했습니다.
```jsx
export { BtnStyle, Button };
```
```css
const BtnComStyle = styled(BtnStyle)`
${BtnStyle};
margin-top: 20px;
`;
```
- 이유 : 없음
- 작업 내역 : LoginEmail.jsx, LoginEmailStyle.jsx , Button.jsx
close : #33

Style : LoginEmail Page UI 제작

---

src/pages/NotFound/NotFound.jsx
src/pages/NotFound/NotFoundStyle.jsx

- 이전페이지 이동 기능은 기능 구현 때 진행하겠습니다.
- 없음
- 작업 내역 : 404 오류에 제공될 페이지 UI를 제작했습니다.
close : #22

Style : 404페이지 UI 제작

---

src/components/FollowUserList/FollowUserList.jsx
src/components/FollowUserList/FollowUserListStyle.jsx
src/pages/Main/Profile/MyProfile/FollowList/FollowList.jsx

- 없음
- 없음
- 작업 내역 : pages/Main/Profile/MyProfile/FollowList.jsx, src/components/FollowUserList/FollowUserList.jsx, FollowUserListStyle.jsx
close : #26

Style : Followers/Following page

---

src/components/ProductList/ProductList.jsx
src/components/ProductList/ProductListStyle.jsx

- Profile page에 사용될 ProductList 컴포넌트입니다.
- 없음
- 작업 내역 : src/components/ProductList폴더, ProductList.jsx, ProductListStyle.jsx
close : #25

Style : ProductList 컴포넌트 UI 제작

---

src/components/Input/Input.jsx
src/components/Input/InputStyle.jsx

-  Input Component 스타일이 아래 이미지로 변경되었습니다.
- 이유 : 피그마 디자인과 다르게 구현했었기 때문입니다.
- 작업 내역 : Input.jsx, InputStyle.jsx

Modify : Input Component 스타일 변경

---

src/components/Input/Input.jsx
src/components/Input/InputStyle.jsx

Revert "Modify : Input Component 스타일 변경"

---

src/components/Input/Input.jsx
src/components/Input/InputStyle.jsx

Modify : Input 스타일 변경

---

src/components/Button/Button.jsx
src/components/Header/TopUploadNav/TopUploadNav.jsx

- `<TopUploadNav size="m" variant="able">
저장
</TopUploadNav>` 로 사용가능합니다. size와 variant에 대한 내용은 Button.jsx 컴포넌트에서 확인가능하며 '저장'이라고 한 부분은 자신이 사용할 버튼 문구로 작성해서 사용하실 수 있습니다.
- 이유 : 사용자가 원하는 버튼으로 헤더에 붙여서 사용할 수 있게 수정했습니다.
- 작업 내역 : TopUploadNav.jsx, TopUploadNavStyle.jsx
- 유연한 버튼 헤더를 사용할 수 있습니다.
close : #47

Modify : Header Component UI

---

src/pages/Main/Post/PostUpload/PostUpload.jsx
src/pages/Main/Post/PostUpload/PostUploadStyle.jsx

- 이미지 업로드 파일 버튼은 추후 기능 추가하며 연두색으로 바뀔 예정입니다.
- 이유 : 없습니다.
- 작업 내역 : 
/Post/PostUpload/PostUpload.jsx
/Post/PostUpload/PostUploadStyle.jsx
close : #58

Style : PostUpload 페이지 UI 제작

---

src/components/Input/Input.jsx
src/components/Input/InputStyle.jsx
src/components/ProductImgUpload/ProductImgUpload.jsx
src/components/ProductImgUpload/ProductImgUploadStyle.jsx
src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEditStyle.jsx
src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUploadStyle.jsx
src/pages/Signup/Signup.jsx
src/pages/Signup/SignupStyle.jsx
src/pages/Signup/SignupUserProfile.jsx
src/pages/Signup/SignupUserProfileStyle.jsx
src/styles/GlobalStyles.jsx

- Signup Page 제작을 위해 이메일로 회원가입 페이지와 프로필설정 페이지를 만들었습니다.
- 이유 : 없습니다.
- 작업 내역 : Signup.jsx, SignupStyle.jsx, SignupUserProfile.jsx, SignupUserProfileStyle.jsx
- Signup.jsx
- SignupUserProfile.jsx
close : #35

Style : Signup Page UI 제작

---

src/components/Input/Input.jsx
src/components/Input/InputStyle.jsx
src/components/ProductImgUpload/ProductImgUpload.jsx
src/components/ProductImgUpload/ProductImgUploadStyle.jsx
src/pages/Main/Home/Search/Search.jsx
src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEditStyle.jsx
src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUploadStyle.jsx
src/styles/GlobalStyles.jsx

- 검색창 페이지 UI를 제작하였습니다.
- 이유 : 변경사항 없습니다.
- 작업 내역 : Search.jsx
- 검색창 구현 화면
close : #56

Style : Search Page UI 제작

---

src/App.jsx
src/components/Nav/Nav.jsx
src/pages/Login/LoginEmail/LoginEmail.jsx
src/pages/Login/LoginEmail/LoginEmailStyle.jsx
src/pages/Main/Chat/Chat.jsx
src/pages/Main/Home/Home.jsx
src/pages/Main/Home/Search/Search.jsx
src/pages/Main/Profile/MyProfile/MyProfile.jsx
src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEditStyle.jsx
src/pages/Root.jsx
src/pages/Signup/Signup.jsx

- Nav bar가 필요하지 않은 페이지와 Nav bar가 필요한 페이지를 구분하여 Router 기능을 구현했습니다
Nav bar가 필요한 페이지는 Outlet을 이용했습니다. 
- 이유 : 없음
- 작업 내역 : App.jsx 및 Router 관련 모든 파일
close : #20

Feat: Router 기능 구현

---

src/pages/Login/LoginEmail/LoginEmail.jsx
src/pages/Login/LoginEmail/LoginEmailStyle.jsx
src/pages/Login/LoginStyle.jsx

- className으로 스타일 주는 방법을 공부해야겠습니다..
- 이유 : module not found 에러 해결하기 위해서 입니다.
- 작업 내역 : LoginEmail.jsx , LoginEmailStyle.jsx, LoginStyle.jsx

Modify : module not found 에러 해결

---

src/pages/Main/Chat/Chat.jsx
src/pages/Main/Post/Post.jsx
src/pages/Main/Post/PostUpload/PostUpload.jsx
src/pages/Main/Profile/MyProfile/MyProfile.jsx

- 충돌 코드 해결 중 잘못 수정되거나 누락된 코드를 원상복귀 시켰습니다.
- 없음
- 작업 내역 : src/pages/Main/Chat/Chat.jsx
- src/pages/Main/Post/Post.jsx
- src/pages/Main/Post/PostUpload/PostUpload.jsx
- src/pages/Main/Profile/MyProfile/MyProfile.jsx
- 현재 발생하는 에러를 제거합니다.
close : #

Modify : 페이지의 header 컴포넌트 링크 업데이트

---

src/_state/auth.js
src/api/api.js
src/components/Nav/NavItem.jsx
src/pages/Login/LoginEmail/LoginEmail.jsx
src/pages/Root.jsx

- 로그인 시 로컬 스토리지에 토큰정만 저장하는 것이 아닌 user를 정보 모두 저장할 수 있도록 수정했습니다.
- 이유 : 가독성을 높이기위해 함수 분리하였습니다.
- 작업 내역 : files changes 참고 부탁드립니다.
close : #82

Modify: login 기능 수정

---

src/components/Button/Button.jsx
src/components/PostCardList/PostCardList.jsx
src/pages/Main/Home/Home.jsx

- onClick props가 존재할 때 onClick()을 실행하도록 변경했습니다.
- 이유 : 에러해결을 위해
- 작업 내역 : Button.jsx
close : #

Modify : Button 에러 해결

---

src/App.jsx
src/components/FollowersCount/FollowersCount.jsx
src/components/Nav/Nav.jsx
src/components/PostCard/PostCard.jsx
src/components/PostCardList/PostCardList.jsx
src/components/Profile/Profile.jsx
src/components/ProfileAccount/ProfileAccount.jsx
src/components/ProfileImg/ProfileImg.jsx
src/components/ProfileImgAccount/ProfileImgAccount.jsx
src/pages/Main/Home/Home.jsx
src/pages/Main/Profile/MyProfile/MyProfile.jsx
src/pages/Main/Profile/UserProfile/UserProfile.jsx

- 다른 user의 프로필 클릭 시 해당 유저의 프로필 화면으로 이동됩니다.(Link)
- 이유 : x
- 작업 내역 : *
- x
close : #96

Feat : Profile Page 내 게시글 및 프로필 보여주기 기능

---

src/components/Chat/ChatListItem/ChatListItem.jsx

- Chat.jsx 에서 사용되는 profileimgaccount.jsx 삭제 후 새로운 컴포넌트로 수정이 필요합니다. 잠시 에러를 위해 주석처리 해놓았습니다.
- 이유 : x
- 작업 내역 : ChatListItem.jsx
- x
close : #

Modify : ProfileImgAccount 컴포넌트 주석처리

---

src/pages/Login/LoginEmail/LoginEmail.jsx

- 로그인 input 작성 시 로그인 버튼이 활성화됩니다(아이디, 비밀번호 입력 중 한개라도 입력되면 활성화되기 때문에 추후 보완이 필요합니다)
- 가입된 로그인 정보가 아닌 경우 validation 메세지가 input 아래 노출됩니다.
- 이유 : 통일성을 위해 fetch => axios 통신방법으로 변경했습니다. 
- 작업 내역 : LoginEmail.jsx
close : #91

Feat : login validation

---

.eslintrc.js
src/components/UploadProfileImg/UploadProfileImg.jsx
src/components/UploadProfileImg/UploadProfileImgStyle.jsx
src/pages/Signup/Signup.jsx
src/pages/Signup/SignupStyle.jsx
src/pages/Signup/SignupUserProfile.jsx
src/pages/Signup/SignupUserProfileStyle.jsx

- API를 이용하여 유저ID 중복 확인 기능과, 프로필 이미지 업로드 기능 및 회원가입 기능을 추가했습니다. 
- 이유 : 회원가입에 필요한 회원 정보를 전달하기 위해 기능을 구현하였습니다.
- 작업 내역 : eslintrc.js, Signup.jsx, SignupStyle.jsx, SignupUserProfile.jsx, SignupUserProfileStyle.jsx UploadProfileImg.jsx, UploadProfileImgStyle.jsx
- 이메일로 회원가입 페이지와 프로필 설정 페이지의 요구사항대로 사용이 가능합니다.
close : #81

Feat : 회원가입 폼 유효성 검증 기능 구현

---

src/pages/Main/Profile/MyProfile/MyProfile.jsx
src/pages/Main/Profile/UserProfile/UserProfile.jsx

- userprofile.jsx 파일에서 에러 메세지 코드 통일했습니다.
- 이유 : 없습니다.
- 작업 내역 : 
src/pages/Main/Profile/MyProfile/MyProfile.jsx
src/pages/Main/Profile/UserProfile/UserProfile.jsx
close : #110

Feat : my_profile 페이지에 product list 불러오는 기능 추가

---

src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx

- 프로필 수정 페이지에서 사용자 정보를 getValue를 통해 불러오고, 이미지를 바꾸지 않았을 경우 사용중인 이미지로 사용할 수 있도록 수정하였습니다.
- 이유 : 프로필 수정 페이지에서 사용자 정보를 제대로 불러오지 못하고 이미지를 바꾸지 않았을 경우 사용중인 이미지로 교체할 수 있도록 수정하였습니다.
- 작업 내역 : ProfileEdit.jsx
close : #101

Modify : Profile Edit Page Read

---

src/components/Comment/Comment.jsx
src/components/Comment/CommentStyle.jsx
src/components/CommentInput/CommentInput.jsx
src/components/CommentInput/CommentInputStyle.jsx
src/components/Modal/CommentModel/CommentAlert.jsx
src/components/Modal/CommentModel/CommentAlertStyle.jsx
src/components/Modal/CommentModel/CommentModal.jsx
src/components/Modal/CommentModel/CommentModalStyle.jsx
src/components/PostTxt/PostTxt.jsx
src/pages/Main/Post/Post.jsx

- 모달과 알림창의 경우 삭제와 신고 두가지를 한 파일에서 처리하기 위해 관련 로직이 변경되었습니다. 
- 새로고침없이 삭제와 등록 업데이트를 구현했습니다. 상품 삭제와 같은 기능에도 동일하게 적용 및 수정할 예정입니다.
- 로그인한 유저의 프로필 이미지 전역 처리가 필요해보입니다.
- Header.jsx 컴포넌트의 z-index 스타일 수정이 필요합니다.
- 이유 : 없습니다.
- 작업 내역 : Files changed 참고 부탁드립니다.
close : #124

Feat : 게시글 상세 페이지 댓글 구현

---

src/components/ChatIcon/ChatIcon.jsx
src/components/PostAlbumList/PostAlbumList.jsx
src/components/Profile/Profile.jsx
src/components/ShareIcon/ShareIcon.jsx
src/pages/Main/Profile/MyProfile/MyProfile.jsx
src/pages/Main/Profile/UserProfile/UserProfile.jsx

- 마이프로필 클릭 후 url에 로그인하지 않은 accountname 입력 시(ex: 로그인한 유저의 account가 pung 일 때, url에 `my_profile/gon`) 
NotFound 페이지가 렌더링 되도록 했습니다.
- 이유 : 수정 및 보완을 위해
- 작업 내역 : changed files 참고 부탁드립니다.
close : #139

Modify : Myprofile_Page 및 UserProfile_Page 수정 및 보완 

---

src/components/Input/Input.jsx
src/components/Modal/ProductModalAlert/ProductAlert.jsx
src/components/Modal/ProductModalAlert/ProductModal.jsx
src/components/Product/Product.jsx
src/components/Product/ProductStyle.jsx
src/components/ProductList/ProductList.jsx
src/components/ProductList/ProductListStyle.jsx
src/pages/Main/Profile/MyProfile/MyProfile.jsx
src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEditStyle.jsx
src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUploadStyle.jsx

Product 관련 이슈들을 해결한 PR입니다. 큰 수정 사항은 다음과 같습니다.
- 없음
- 이유 : Input 컴포넌트의 `min` `max` props를 `minLength ` `maxLength`로 수정했습니다.
- 상품 업로드 및 수정 시 사용자가 유효성을 판단 할 수 있는 문장을 추가했습니다.
- `parseInt`의 경우 빈 문자열일 경우 `NaN`을 출력하고, `Number`의 경우 문자 입력시 `NaN`를 출력하기 때문에 금액을 입력하는 Input에서 이슈가 있었습니다. 이와 관련하여 `Number.isNaN`를 사용하여 해결하고, 사용자에게 10자리 이상의 금액을 입력하도록 유효 조건을 변경했습니다.
- 상품 이미지 업로드 및 수정시 미리보기 데이터를 fileReader API로 처리하는 방식으로 변경했습니다. 이는 불필요한 데이터 전송을 줄이기 위함입니다.
- '업로드' 버튼의 URL이 잘못되어있어 수정했습니다.
- 상품 삭제 시 새로고침 되지 않고 화면에서 바로 삭제되게 수정했습니다.
- 기타 주석과 사용하지 않는 코드들을 삭제했습니다.
- 상품 카드에 border를 추가하여 작은 사이즈의 이미지를 업로드 할 경우에도 일정한 레이아웃이 제공되도록 수정했습니다.
- 작업 내역 : Files changed를 참고해주세요.
- 상품 등록 및 수정 시 사용자에게 더 나은 경험을 제공합니다.
close : #146

Modify : Product관련 이슈 해결

---

src/components/PostCard/PostCard.jsx
src/components/ProfileImgAccount/ProfileImgAccount.jsx

- ProfileImgAccount 중복 사용으로 인한 에러 해결
- 이유 : 
- 작업 내역 : PostCard.jsx
- 
close : #

Modify : Post 이미지 에러 해결

---

src/App.jsx

- path 에러를 수정했습니다.
- 이유 : '{'가 빠져 있었습니다.
close : #120

Modify : path 에러 수정

---

src/App.jsx
src/components/PostCard/PostCard.jsx
src/pages/Main/Post/PostEdit/PostEdit.jsx

- 게시글 상세페이지 에러 해결
- 이유 : 
- 작업 내역 : PostCard.jsx
- 
close : #

Modify : 게시글 상세페이지 에러 해결

---

src/components/Blank/Blank.jsx
src/components/HomeRender/HomeRenderBlank.jsx
src/pages/Loading/Loading.jsx
src/pages/Loading/LoadingStyle.jsx
src/pages/Main/Home/Home.jsx
src/pages/Main/Home/Search/Search.jsx
src/pages/Main/Post/Post.jsx
src/pages/Main/Post/PostUpload/PostUpload.jsx
src/pages/Main/Profile/FollowerList/FollowerList.jsx
src/pages/Main/Profile/MyProfile/FollowingList/FollowingList.jsx
src/pages/Main/Profile/MyProfile/MyProfile.jsx
src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
src/pages/Main/Profile/UserProfile/UserProfile.jsx
src/pages/NotFound/NotFound.jsx

- 데이터 get 해오는 페이지 기준으로 로딩 페이지 추가 해두었습니다.
- 홈 피드에서 1초간 비어있는 페이지가 나오는 이유가 로딩페이지의 부재때문임을 알게되어 두 이슈를 함께 작업했습니다.
- 이유 : 검색 프로필 이미지 높이 값이 빠져 있어 추가해주었습니다.
- 작업 내역 : Files changed 참고해주세요.
close : #153 
close : #150

Modify : Home 조건부 렌더링 오류 수정 및 로딩페이지 제작

---

src/pages/Main/Profile/UserProfile/UserProfile.jsx

- 상동
- 이유 : 상동
- 작업 내역 : UserProfile.jsx
close : #

Modify : 프로필에 따른 판매중인 상품 보여주기

---

src/pages/Main/Profile/FollowerList/FollowerList.jsx
src/pages/Main/Profile/MyProfile/FollowingList/FollowingList.jsx

- 팔로워, 팔로잉 목록 limit 를 100명으로 수정했습니다.
- 이유 : 팔로워, 팔로잉 목록이 기본적으로 10명으로 제한되어있기때문에 수정해주었습니다.
- 작업 내역 : FolloewList.jsx, FollowingList.jsx
- /:accountname/follower, /:accountname/following
close : #170

Modify : follow limit

---

src/api/Feed/createPost.js
src/api/Feed/deleteAPI.js
src/api/Profile/getMyProfile.js
src/api/api.js
src/api/deleteAPI.js
src/api/getAPI.js
src/api/putAPI.js
src/components/Modal/PostModalAlert/PostDeleteAlert.jsx
src/pages/Main/Post/PostEdit/PostEdit.jsx
src/pages/Main/Post/PostUpload/PostUpload.jsx

- 기존 api.js 기본 주소인 url 이름을 baseUrl로 수정했습니다.
`export const baseUrl = 'https://mandarin.api.weniv.co.kr/';`
- getAPI, putAPI, deleteAPI를 공통으로 사용할 수 있도록 만들어 중복코드를 최소화합니다.
- 내 프로필 불러오는 통신을 api/Profile/getMyProfile.js로 추가했습니다.
- 이유 :  서버와 통신하는 api를 따로 분리하여 복잡성을 낮추고자 합니다.
- 작업 내역 : 
src/api/api.js
src/api/Feed/createPost.js
src/api/Profile/getMyProfile.js
src/api/getAPI.js
src/api/putAPI.js
src/api/deleteAPI.js
src/pages/Main/Post/PostUpload/PostUpload.jsx
src/pages/Main/Post/PostEdit/PostEdit.jsx
src/components/Modal/PostModalAlert/PostDeleteAlert.jsx
close : #182

Refactor : 게시글 등록, 수정, 삭제 api 분리

---

src/api/Product/deleteProduct.js
src/api/Product/getProduct.js
src/api/Product/putProduct.js
src/api/Product/uploadProduct.js
src/components/Modal/ProductModalAlert/ProductAlert.jsx
src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx

- try-catch문 전체가 분리되어있습니다. 추후 전체 코드의 방향성과 맞지 않다면 다시 수정을 진행하겠습니다.
- 이유 : 코드의 가독성을 위해 API 코드를 분리하여 별도의 파일로 생성해두었습니다.
- 작업 내역 : Files changed 참고 부탁드립니다.
- 코드의 가독성과 반복되는 코드의 재활용성을 높입니다. 
#187

Refactor : Product api 분리

---

src/api/Comment/deleteComment.js
src/api/Comment/getComment.js
src/api/Comment/postComment.js
src/api/Comment/reportComment.js
src/api/Post/getPost.jsx
src/api/getAPI.js
src/components/Comment/Comment.jsx
src/components/CommentInput/CommentInput.jsx
src/pages/Main/Post/Post.jsx
src/pages/Main/Post/PostStyle.jsx

- 상세 게시글 페이지인 Post.jsx에 사용된 게시물 get api가 수정되어 있지 않아 함께 리팩토링을 진행했습니다.
- 이유 : 코드의 가독성을 위해 API 코드를 분리하여 별도의 파일로 생성해두었습니다.
- 작업 내역 : Files changed 참고 부탁드립니다.
- 코드의 가독성과 반복되는 코드의 재활용성을 높입니다.
- 
#187

Refactor : Comments api 분리

---

.netlify/state.json
src/api/Login/postUserLogin.js
src/pages/Login/LoginEmail/LoginEmail.jsx

Refactor : Login API 분리

---

.netlify/state.json
src/api/Feed/getFollowFeed.js
src/api/Search/getSearchUser.js
src/api/api.js
src/pages/Main/Home/Home.jsx
src/pages/Main/Home/Search/Search.jsx

- try-catch문 전체를 분리했습니다.
- 이유 : 코드의 가독성을 위해 API 코드를 분리하여 별도의 파일로 생성해두었습니다.
- 작업 내역 : Files changed 참고 부탁드립니다.
- 코드의 가독성과 반복되는 코드의 재활용성을 높입니다.
close : #187

Refactor : Search API 분리

---

src/api/Feed/deleteLiked.js
src/api/Feed/postLiked.js
src/components/HeartIcon/HeartIcon.jsx

- 없습니다.
- 이유 : 서버와 통신하는 api를 따로 분리하여 복잡성을 낮추고자 합니다.
- 작업 내역 : 
src/api/Feed/postLiked.js
src/api/Feed/deleteLiked.js
src/components/HeartIcon/HeartIcon.jsx
#182

Refactor : 좋아요 기능, 취소 api 분리

---

src/api/Feed/deletePost.js
src/components/common/Modal/PostModalAlert/PostDeleteAlert.jsx

- 누락된 deleteAPI 코드를 수정했습니다.
- 이유 : 이전의 공통 api 코드를 사용하지 않고 코드 분리
- 작업 내역 : 
src/api/Feed/deletePost.js
src/components/common/Modal/PostModalAlert/PostDeleteAlert.jsx
close : #182

Refactor : deletePost api 코드 수정

---

src/api/Feed/getFollowFeed.js
src/pages/Main/Home/Home.jsx

- Home.jsx 페이지에 있는 주석을 삭제했습니다.
- getFollowFeed api 파일에 try문 에러 처리까지 분리했습니다.
- 이유 : 가독성 향상 및 유지보수 용이하도록 코드 정리
- 작업 내역 : 
src/api/Feed/getFollowFeed.js
src/pages/Main/Home/Home.jsx
close : #182

Refactor : Home 페이지 getFollowFeed api 정리

---

src/components/common/Modal/PostModalAlert/PostDeleteAlert.jsx
src/pages/Main/Post/PostEdit/PostEdit.jsx

- 이유 : api 분리시 누락되었던 코드를 수정했습니다
- 작업 내역 : 
src/components/common/Modal/PostModalAlert/PostDeleteAlert.jsx
src/pages/Main/Post/PostEdit/PostEdit.jsx

Modify : 게시물 기존 이미지 업로드 및 게시글 삭제 코드 수정

---

src/components/FollowUserList/FollowUserList.jsx
src/components/common/ProfileImgAccount/ProfileImgAccount.jsx

- 내 프로필 팔로잉 버튼 히든 처리했습니다
- 이유 : UI 개선을 위해 수정했습니다.
- 작업 내역 : ProfileImgAccount.jsx, FollowUserList.jsx
- 
close : #213

Refactor : 내 프로필 팔로잉 버튼 hidden 처리

---

src/components/PostAlbum/PostAlbum.jsx
src/pages/Login/Login.jsx
src/pages/Login/LoginStyle.jsx
src/pages/Main/Chat/ChatRoom/ChatRoom.jsx
src/pages/Main/Chat/ChatRoom/ChatRoomStyle.jsx
src/pages/Main/Post/PostUpload/PostUpload.jsx
src/pages/Main/Post/PostUpload/PostUploadStyle.jsx
src/pages/NotFound/NotFound.jsx

- section 마다 heading tag 추가 작업했습니다.
- 이유 : 
- 작업 내역 : 
- 
close : #211

Refactor : section에 heading tag 작성

---

src/api/Profile/getUserFollowerList.js
src/pages/Main/Profile/UserProfile/UserProfile.jsx

- 상동
- 이유 : 상동
- 작업 내역 : changed files 확인 부탁드립니다.
- 
close : #218

Refactor: 팔로우 버튼 클릭 시 팔로워 수 새로고침 안되는 문제 해결

---

src/components/HeartIcon/HeartIconStyle.jsx
src/components/common/Header/Header.jsx

- 모바일 환경에서 크기가 다른 이미지의 크기를 고정했습니다.
- 이유 :
- 작업 내역 : Header.jsx, HeartIconStyle.jsx
- 모바일 환경에서도 이미지의 크기가 다르지 않게 보여집니다.
close : #210

Refactor : 모바일 환경 이미지 크기 수정

---

.eslintrc.js
src/components/ShareIcon/ShareIcon.jsx
src/pages/Login/Login.jsx
src/pages/Main/Profile/UserProfile/UserProfile.jsx
src/pages/NotFound/NotFound.jsx

- 몇가지 에러와 관련하여 수정을 진행했습니다. 상세 사항은 하단의 `변경사항 및 이유` 참고 부탁드립니다.
1. **.eslintrc.js**
확장자와 관련하여 Compile error가 발생하여 하단의 코드를 추가해주었습니다.
```jsx
'import/prefer-default-export': 'off' // => 추가
'import/extensions': ['off'] //  => 변경, import 확장자 작성 관련. off 로 하면 확장자를 반드시 명시하도록 하는것
```
2. **src/pages/Login/Login.jsx**
import 순서 관련 에러가 생겨 MetaDatas import 순서를 변경해주었습니다.
3. **src/pages/NotFound/NotFound.jsx**
개행과 관련하여 eslint 에러가 생겨 수정해주었습니다.
4. **src/components/ShareIcon/ShareIcon.jsx**
해당 컴포넌트의 value 속성에서 에러가 확인되어 defaultValue로 수정해주었습니다.
5. **src/pages/Main/Profile/UserProfile/UserProfile.jsx**
MetaDatas에 사용될 username을 비동기 처리 전 로드하는 문제로 에러가 생겨 수정해주었습니다.
- 작업 내역 : 상단 `변경사항 및 이유`와 동일
- 현재 발생된 Compile error와 Runtime error를 모두 해결합니다.
close : #232

Modify : Error resolving

---

package-lock.json
package.json
src/index.js

- react-helmet 설정 당시 pre-rendering을 위해 사용된 react-snap과 hydration에서 치명적인 버그가 발견되어 코드를 전부 제거했습니다. 추후 문제점을 보완하여 다시 코드를 작성할 예정입니다.
- 이유 : 전달사항 참고
- package-lock.json
- package.json
- src/index.js
- 페이지들의 정상적인 출력
close : #236

Modify : react-snap과 hydration 제거

---

src/components/Common/Alert/AlertStyle.jsx
src/components/Common/Alert/CommentAlert.jsx
src/components/Common/Alert/LoginAlert.jsx
src/components/Common/Alert/PostDeleteAlert.jsx
src/components/Common/Alert/PostReportAlert.jsx
src/components/Common/Alert/ProductAlert.jsx
src/components/Common/Button/Button.jsx
src/components/Common/Button/ButtonStyle.jsx
src/components/Common/Header/Header.jsx
src/components/Common/Header/HeaderStyle.jsx
src/components/Common/Input/Input.jsx
src/components/Common/Input/InputStyle.jsx
src/components/Common/Modal/CommentModal.jsx
src/components/Common/Modal/LoginModal.jsx
src/components/Common/Modal/LoginModalAlert/LoginAlert.jsx
src/components/Common/Modal/LoginModalAlert/LoginAlertStyle.jsx
src/components/Common/Modal/ModalStyle.jsx
src/components/Common/Modal/PostModal.jsx
src/components/Common/Modal/PostReportModal.jsx
src/components/Common/Modal/ProductModal.jsx
src/components/Common/Nav/Nav.jsx
src/components/Common/Nav/NavStyle.jsx
src/components/Common/ProfileAccount/ProfileAccount.jsx
src/components/Common/ProfileAccount/ProfileAccountStyle.jsx
src/components/Common/ProfileImg/ProfileImg.jsx
src/components/Common/ProfileImg/ProfileImgStyle.jsx
src/components/Common/ProfileImgAccount/ProfileImgAccount.jsx
src/components/Common/ProfileImgAccount/ProfileImgAccountStyle.jsx
src/components/Common/UploadFileBtn/UploadFileBtn.jsx
src/components/Common/UploadFileBtn/UploadFileBtnStyle.jsx

- git의 기본설정은 파일, 폴더의 대소문자를 구분하지 않습니다. 따라서 지난번 #234 PR에서의 common => Common으로의 폴더명 변경이 Repository에 반영되지 않아 컴포넌트들을 import 해오지 못하는 에러가 발생했습니다. 다음과 같은 git 설정으로 대소문자를 인식하도록 변경해주었습니다.
```
git config core.ignorecase false
```
- 이유 : 전달사항 참조
- 작업 내역 : common => Common 폴더명 수정
- import error 제거
close : #

Modify : common 폴더명 수정
